// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwSPLIaNJDOdskUBhsC31tcaQx8D8bNIs',
    appId: '1:277917627575:android:02df5ee0602a98ba710932',
    messagingSenderId: '277917627575',
    projectId: 'mynoteflow',
    storageBucket: 'mynoteflow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApOFs6tI2ccubJ-Sf2tIjnTRO6eWp1EW0',
    appId: '1:277917627575:ios:806e039a82307b0b710932',
    messagingSenderId: '277917627575',
    projectId: 'mynoteflow',
    storageBucket: 'mynoteflow.firebasestorage.app',
    iosBundleId: 'com.example.riverpodLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUvb1SaeiXHesw0sBkK6d4bHLxruQBmaY',
    appId: '1:277917627575:web:dba0a4667020c92b710932',
    messagingSenderId: '277917627575',
    projectId: 'mynoteflow',
    authDomain: 'mynoteflow.firebaseapp.com',
    storageBucket: 'mynoteflow.firebasestorage.app',
    measurementId: 'G-0FB0DQFY8Q',
  );
}
